platform :ios, '13.0'

inhibit_all_warnings!

target 'HeartRecording' do
	use_frameworks!

	pod 'ReactiveCocoa', '11.1.0'
	pod 'FFPopup', '1.1.4'
  pod 'DeviceKit', '4.2.1'
	pod 'SwiftyStoreKit', '0.16.1'
	pod 'SnapKit'

end

post_install do |pi|
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"
        config.build_settings['SWIFT_SUPPRESS_WARNINGS'] = 'YES'
      end
    end
end
